
spring.datasource.url=jdbc:postgresql://db:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC

supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=${SUPABASE_BUCKET}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.cache.type=jcache
spring.cache.jcache.provider=com.hazelcast.cache.impl.HazelcastServerCachingProvider
spring.cache.jcache.config=classpath:hazelcast.xml

bucket4j.enabled=true

bucket4j.filters[0].cache-name=mensagemRateLimit
bucket4j.filters[0].url=/api/.*
bucket4j.filters[0].filter-order=1

bucket4j.filters[0].rate-limits[0].execute-condition=@minisocialSecurity.estaAutenticado()
bucket4j.filters[0].rate-limits[0].cache-key=@minisocialSecurity.getUsuario()

bucket4j.filters[0].rate-limits[0].bandwidths[0].capacity=20
bucket4j.filters[0].rate-limits[0].bandwidths[0].time=1
bucket4j.filters[0].rate-limits[0].bandwidths[0].unit=minutes
bucket4j.filters[0].rate-limits[0].bandwidths[0].refill-speed=interval

bucket4j.filters[1].cache-name=mensagemRateLimit
bucket4j.filters[1].url=.*
bucket4j.filters[1].filter-order=2

bucket4j.filters[1].rate-limits[0].execute-condition=!@minisocialSecurity.estaAutenticado()
bucket4j.filters[1].rate-limits[0].cache-key=@minisocialSecurity.getRemoteAddr()

bucket4j.filters[1].rate-limits[0].bandwidths[0].capacity=5
bucket4j.filters[1].rate-limits[0].bandwidths[0].time=1
bucket4j.filters[1].rate-limits[0].bandwidths[0].unit=minutes
bucket4j.filters[1].rate-limits[0].bandwidths[0].refill-speed=interval