spring.datasource.url=jdbc:postgresql://localhost:5432/db_mini_rede_social
spring.datasource.username=postgres
spring.datasource.password=2002
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

supabase.url=https://bznoabgvahphhaeoextu.supabase.co
supabase.key=sb_secret_1Ay4ZY3NxeBNscXy1JHbTw_weS-TcPa
supabase.bucket=postagens


